# Generated by Django 5.0.7 on 2024-09-26 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ing', models.TextField(max_length=500)),
                ('cook', models.TextField(max_length=500)),
                ('cat', models.CharField(choices=[('soup', 'soup'), ('starters', 'starters'), ('main course', 'main course'), ('dessert', 'dessert')], max_length=20)),
                ('img', models.ImageField(upload_to='chef')),
                ('cus_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
