# Generated by Django 5.0.7 on 2024-09-30 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='fav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_fav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.recipe')),
            ],
        ),
    ]
