# Generated by Django 5.0.7 on 2024-09-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_fav'),
    ]

    operations = [
        migrations.AddField(
            model_name='fav',
            name='view',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
