# Generated by Django 5.0.7 on 2024-09-30 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_view_fav_viewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fav',
            old_name='viewer',
            new_name='name',
        ),
    ]
