# Generated by Django 5.0.7 on 2024-10-02 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_viewer_fav_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('rec_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.recipe')),
            ],
        ),
    ]
