# Generated by Django 5.0.7 on 2024-10-02 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fav',
            name='rec_fav',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.recipe'),
        ),
    ]
