# Generated by Django 5.0.7 on 2024-10-02 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_fav_rec_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fav',
            name='rec_fav',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.recipe'),
        ),
    ]
